In [1]:
print('hello')

hello

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [64]:
df = pd.read_excel('real_estate_regression.xlsx')
df.head(2)

,Property_ID,Location,Size_sqft,Bedrooms,Bathrooms,Year_Built,Garage,Nearby_Schools,Crime_Rate,Transport_Accessibility,Green_Space_Availability,Local_Amenities,HOA_Fees,Property_Tax,Average_Income_Area,Internet_Availability,Electricity_Availability,Construction_Quality,Property_Price
0,448b180f-86b2-4453-9469-7e3f7276d9db,Rural,2333.0,5.0,3.0,2005.0,No,1.0,0.89,2.0,1.0,1.0,458.0,9349.0,69644.0,Average,Unreliable,High,419947.0
1,b8572293-f341-45fe-97eb-5d1edf1da20e,Urban,NaN,1.0,3.0,1958.0,NaN,2.0,2.90,1.0,1.0,4.0,293.0,8030.0,79819.0,Poor,Reliable,Medium,306216.0

In [65]:
df = df.drop(columns=['Property_ID'])
df.head(2)

,Location,Size_sqft,Bedrooms,Bathrooms,Year_Built,Garage,Nearby_Schools,Crime_Rate,Transport_Accessibility,Green_Space_Availability,Local_Amenities,HOA_Fees,Property_Tax,Average_Income_Area,Internet_Availability,Electricity_Availability,Construction_Quality,Property_Price
0,Rural,2333.0,5.0,3.0,2005.0,No,1.0,0.89,2.0,1.0,1.0,458.0,9349.0,69644.0,Average,Unreliable,High,419947.0
1,Urban,NaN,1.0,3.0,1958.0,NaN,2.0,2.90,1.0,1.0,4.0,293.0,8030.0,79819.0,Poor,Reliable,Medium,306216.0

In [78]:
df.shape

(20000, 18)

In [66]:
df.isnull().sum()

Location                    1000
Size_sqft                   1000
Bedrooms                    1000
Bathrooms                   1000
Year_Built                  1000
Garage                      1000
Nearby_Schools              1000
Crime_Rate                  1000
Transport_Accessibility     1000
Green_Space_Availability    1000
Local_Amenities             1000
HOA_Fees                    1000
Property_Tax                1000
Average_Income_Area         1000
Internet_Availability       1000
Electricity_Availability    1000
Construction_Quality        1000
Property_Price              1000
dtype: int64

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Location                  19000 non-null  object
 1   Size_sqft                 19000 non-null  float64
 2   Bedrooms                  19000 non-null  float64
 3   Bathrooms                 19000 non-null  float64
 4   Year_Built                19000 non-null  float64
 5   Garage                    19000 non-null  object
 6   Nearby_Schools            19000 non-null  float64
 7   Crime_Rate                19000 non-null  float64
 8   Transport_Accessibility   19000 non-null  float64
 9   Green_Space_Availability  19000 non-null  float64
 10  Local_Amenities           19000 non-null  float64
 11  HOA_Fees                  19000 non-null  float64
 12  Property_Tax              19000 non-null  float64
 13  Average_Income_Area       19000 non-null  float64
 14  Internet_Availability     19000 non-null  object
 15  Electricity_Availability  19000 non-null  object
 16  Construction_Quality      19000 non-null  object
 17  Property_Price            19000 non-null  float64
dtypes: float64(13), object(5)
memory usage: 2.7+ MB

In [69]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Size_sqft,19000.0,2755.151053,1296.449877,500.0,1637.7500,2760.000,3871.25,4999.0
Bedrooms,19000.0,3.004842,1.413275,1.0,2.0000,3.000,4.00,5.0
Bathrooms,19000.0,1.995632,0.814969,1.0,1.0000,2.000,3.00,3.0
Year_Built,19000.0,1985.800474,21.058633,1950.0,1968.0000,1986.000,2004.00,2022.0
Nearby_Schools,19000.0,2.002421,1.417446,0.0,1.0000,2.000,3.00,4.0
Crime_Rate,19000.0,4.982347,2.887178,0.0,2.4575,4.975,7.48,10.0
Transport_Accessibility,19000.0,2.507474,1.121282,1.0,2.0000,3.000,4.00,4.0
Green_Space_Availability,19000.0,2.498105,1.115706,1.0,2.0000,3.000,3.00,4.0
Local_Amenities,19000.0,2.497684,1.114005,1.0,2.0000,2.000,3.00,4.0
HOA_Fees,19000.0,247.688053,143.387266,0.0,124.0000,246.000,371.00,499.0
Property_Tax,19000.0,5491.540842,2596.309640,1000.0,3217.0000,5503.000,7737.00,9998.0
Average_Income_Area,19000.0,89965.160579,34683.584330,30012.0,59996.7500,89738.500,119944.00,149986.0
Property_Price,19000.0,459745.199053,195147.107006,90002.0,292980.2500,460757.000,627888.50,825037.0

In [72]:
nums = df.select_dtypes(include='number')
nums

,Size_sqft,Bedrooms,Bathrooms,Year_Built,Nearby_Schools,Crime_Rate,Transport_Accessibility,Green_Space_Availability,Local_Amenities,HOA_Fees,Property_Tax,Average_Income_Area,Property_Price
0,2333.0,5.0,3.0,2005.0,1.0,0.89,2.0,1.0,1.0,458.0,9349.0,69644.0,419947.0
1,NaN,1.0,3.0,1958.0,2.0,2.90,1.0,1.0,4.0,293.0,8030.0,79819.0,306216.0
2,3993.0,5.0,2.0,2012.0,NaN,5.07,4.0,1.0,1.0,63.0,3419.0,125928.0,669162.0
3,3638.0,1.0,2.0,1953.0,3.0,7.71,4.0,1.0,4.0,250.0,8346.0,58465.0,573927.0
4,3612.0,4.0,3.0,1987.0,3.0,3.44,4.0,2.0,2.0,453.0,6733.0,50182.0,601651.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,4524.0,5.0,2.0,2011.0,1.0,6.55,3.0,4.0,4.0,100.0,2634.0,135100.0,743090.0
19996,3088.0,5.0,3.0,2011.0,0.0,2.96,2.0,3.0,1.0,244.0,5990.0,94603.0,540612.0
19997,4194.0,4.0,2.0,1954.0,NaN,4.10,3.0,2.0,4.0,374.0,8559.0,71309.0,685215.0
19998,3201.0,2.0,1.0,2017.0,0.0,3.80,2.0,2.0,3.0,460.0,8201.0,119740.0,512631.0
19999,1975.0,3.0,2.0,1986.0,0.0,6.98,3.0,4.0,2.0,NaN,1230.0,79947.0,345420.0

In [73]:
for col in nums:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[
        (df[col] < lower) | (df[col] > upper)]

    print(f"{col}: {len(outliers)} outliers")

Size_sqft: 0 outliers
Bedrooms: 0 outliers
Bathrooms: 0 outliers
Year_Built: 0 outliers
Nearby_Schools: 0 outliers
Crime_Rate: 0 outliers
Transport_Accessibility: 0 outliers
Green_Space_Availability: 0 outliers
Local_Amenities: 0 outliers
HOA_Fees: 0 outliers
Property_Tax: 0 outliers
Average_Income_Area: 0 outliers
Property_Price: 0 outliers

In [74]:
nums.skew()

Size_sqft                  -0.013326
Bedrooms                   -0.003753
Bathrooms                   0.008011
Year_Built                  0.010151
Nearby_Schools              0.002158
Crime_Rate                  0.001315
Transport_Accessibility    -0.003550
Green_Space_Availability   -0.000022
Local_Amenities             0.012900
HOA_Fees                    0.015779
Property_Tax               -0.006487
Average_Income_Area         0.009110
Property_Price             -0.015248
dtype: float64

In [75]:
df.duplicated().sum()

np.int64(0)

In [79]:
cols = df.select_dtypes(include='object')
cols

,Location,Garage,Internet_Availability,Electricity_Availability,Construction_Quality
0,Rural,No,Average,Unreliable,High
1,Urban,NaN,Poor,Reliable,Medium
2,Rural,Yes,Good,Reliable,High
3,Rural,No,Poor,Reliable,Medium
4,Urban,No,Good,Reliable,Low
...,...,...,...,...,...
19995,Urban,No,Average,Unreliable,Medium
19996,Rural,No,Good,Unreliable,Medium
19997,Urban,Yes,Good,Reliable,High
19998,NaN,No,Average,Moderate,Low
19999,Urban,No,Average,Unreliable,Medium

In [81]:
df.dropna(subset=['Property_Price'],inplace=True)

In [83]:
col_nums = df.select_dtypes(include='number').columns

for col in col_nums:
    df[col] = df[col].fillna(df[col].mean())

In [84]:
cat_cols = df.select_dtypes(include='object').columns

for i in cat_cols:
    df[i] = df[i].fillna(df[i].mode()[0])

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19000 entries, 0 to 19999
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Location                  19000 non-null  object
 1   Size_sqft                 19000 non-null  float64
 2   Bedrooms                  19000 non-null  float64
 3   Bathrooms                 19000 non-null  float64
 4   Year_Built                19000 non-null  float64
 5   Garage                    19000 non-null  object
 6   Nearby_Schools            19000 non-null  float64
 7   Crime_Rate                19000 non-null  float64
 8   Transport_Accessibility   19000 non-null  float64
 9   Green_Space_Availability  19000 non-null  float64
 10  Local_Amenities           19000 non-null  float64
 11  HOA_Fees                  19000 non-null  float64
 12  Property_Tax              19000 non-null  float64
 13  Average_Income_Area       19000 non-null  float64
 14  Internet_Availability     19000 non-null  object
 15  Electricity_Availability  19000 non-null  object
 16  Construction_Quality      19000 non-null  object
 17  Property_Price            19000 non-null  float64
dtypes: float64(13), object(5)
memory usage: 2.8+ MB

In [86]:
df.sample(10)

,Location,Size_sqft,Bedrooms,Bathrooms,Year_Built,Garage,Nearby_Schools,Crime_Rate,Transport_Accessibility,Green_Space_Availability,Local_Amenities,HOA_Fees,Property_Tax,Average_Income_Area,Internet_Availability,Electricity_Availability,Construction_Quality,Property_Price
16397,Urban,2900.000000,3.000000,3.0,2008.0,Yes,3.0,8.67,2.0,1.000000,1.0,235.000000,4297.000000,89057.0,Average,Reliable,High,493717.0
3179,Urban,3858.000000,3.002493,2.0,2015.0,Yes,1.0,2.86,2.0,2.000000,3.0,192.000000,6106.000000,43693.0,Good,Reliable,Medium,636519.0
11132,Suburban,1077.000000,3.000000,1.0,1952.0,Yes,3.0,8.52,4.0,2.000000,1.0,247.487516,6401.000000,90225.0,Poor,Moderate,High,203805.0
7875,Suburban,2244.000000,3.002493,3.0,1985.0,Yes,1.0,6.83,4.0,4.000000,2.0,433.000000,7763.000000,111971.0,Good,Moderate,Low,410839.0
6666,Suburban,4061.000000,1.000000,1.0,2004.0,No,1.0,9.78,4.0,3.000000,1.0,113.000000,6103.000000,60651.0,Poor,Reliable,Medium,629106.0
7632,Urban,1404.000000,2.000000,3.0,1988.0,No,3.0,9.10,3.0,2.000000,4.0,116.000000,7169.000000,87772.0,Poor,Moderate,Medium,256197.0
9435,Suburban,4827.000000,2.000000,3.0,1976.0,Yes,1.0,7.37,4.0,4.000000,2.0,444.000000,2985.000000,46940.0,Poor,Moderate,Medium,765271.0
13712,Urban,3383.000000,2.000000,3.0,1953.0,No,2.0,2.39,3.0,2.498339,4.0,15.000000,9945.000000,108247.0,Good,Unreliable,Medium,556239.0
8870,Rural,2753.911639,5.000000,3.0,2012.0,No,3.0,6.38,3.0,1.000000,4.0,258.000000,5498.910244,114813.0,Average,Unreliable,Low,675160.0
4266,Urban,640.000000,5.000000,3.0,1976.0,Yes,4.0,6.26,2.0,4.000000,3.0,449.000000,9629.000000,42618.0,Poor,Reliable,High,171186.0

In [87]:
df.columns

Index(['Location', 'Size_sqft', 'Bedrooms', 'Bathrooms', 'Year_Built',
       'Garage', 'Nearby_Schools', 'Crime_Rate', 'Transport_Accessibility',
       'Green_Space_Availability', 'Local_Amenities', 'HOA_Fees',
       'Property_Tax', 'Average_Income_Area', 'Internet_Availability',
       'Electricity_Availability', 'Construction_Quality', 'Property_Price'],
      dtype='object')

In [88]:
change_dtype = ['Bedrooms','Bathrooms','Year_Built','Nearby_Schools','Transport_Accessibility','Green_Space_Availability','Local_Amenities']

In [89]:
df[change_dtype] = df[change_dtype].round().astype(int)
df[change_dtype].head(3)

,Bedrooms,Bathrooms,Year_Built,Nearby_Schools,Transport_Accessibility,Green_Space_Availability,Local_Amenities
0,5,3,2005,1,2,1,1
1,1,3,1958,2,1,1,4
2,5,2,2012,2,4,1,1

In [90]:
round_columns = ['Size_sqft','Property_Tax','Crime_Rate','HOA_Fees','Average_Income_Area','Property_Price']
df[round_columns] = df[round_columns].round(2)
df.sample(10)

,Location,Size_sqft,Bedrooms,Bathrooms,Year_Built,Garage,Nearby_Schools,Crime_Rate,Transport_Accessibility,Green_Space_Availability,Local_Amenities,HOA_Fees,Property_Tax,Average_Income_Area,Internet_Availability,Electricity_Availability,Construction_Quality,Property_Price
6980,Rural,3176.0,1,2,1963,Yes,2,5.32,4,1,4,49.00,4506.0,68107.0,Good,Moderate,Medium,497655.0
5094,Rural,3512.0,4,2,1978,No,1,6.05,1,3,2,412.00,6843.0,123107.0,Good,Reliable,Medium,584616.0
4873,Suburban,3364.0,4,3,2020,No,0,8.36,2,3,4,144.00,8011.0,84642.0,Poor,Moderate,Low,568403.0
15290,Rural,4313.0,1,3,2022,No,1,7.66,3,3,1,247.49,5575.0,51432.0,Average,Reliable,High,682214.0
12736,Rural,2949.0,5,1,1997,No,0,7.98,2,2,4,374.00,9893.0,88288.0,Average,Moderate,Low,496171.0
11421,Urban,3033.0,1,2,1970,No,2,1.35,1,2,2,31.00,1034.0,141518.0,Poor,Moderate,High,481312.0
19359,Suburban,3542.0,5,1,1951,No,0,4.98,4,2,4,195.00,2772.0,48294.0,Average,Moderate,Low,587562.0
3416,Urban,1178.0,2,3,1999,No,0,0.48,4,4,2,63.00,9531.0,32807.0,Poor,Unreliable,High,222351.0
17620,Urban,2038.0,5,2,2008,No,0,4.98,3,3,4,361.00,5437.0,121763.0,Poor,Moderate,High,368297.0
16017,Urban,4037.0,3,2,1961,Yes,1,9.61,4,2,1,53.00,3992.0,118781.0,Good,Unreliable,High,650327.0

In [91]:
df.to_csv('house_price_cleaned.csv', index=False)

In [92]:
df.corr(numeric_only=True)['Property_Price'].sort_values(ascending=False)

Property_Price              1.000000
Size_sqft                   0.971805
Bedrooms                    0.070582
Bathrooms                   0.040136
Property_Tax                0.011236
Crime_Rate                  0.007228
Nearby_Schools              0.005353
Average_Income_Area         0.003949
Green_Space_Availability   -0.002543
Year_Built                 -0.003380
Local_Amenities            -0.003982
Transport_Accessibility    -0.011831
HOA_Fees                   -0.012974
Name: Property_Price, dtype: float64

In [93]:
df.columns

Index(['Location', 'Size_sqft', 'Bedrooms', 'Bathrooms', 'Year_Built',
       'Garage', 'Nearby_Schools', 'Crime_Rate', 'Transport_Accessibility',
       'Green_Space_Availability', 'Local_Amenities', 'HOA_Fees',
       'Property_Tax', 'Average_Income_Area', 'Internet_Availability',
       'Electricity_Availability', 'Construction_Quality', 'Property_Price'],
      dtype='object')

In [97]:
df['Size_sqft'].min()

500.0